apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigsecret
  namespace: cinemaabyss
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJjM0JwYm1Wc09tZG9jRjgzUm5KYVNrdGlabGhQVEc5aFp6QnVWRXB6YWtaaGJWRm1jMFZpTlc0elpHOWlOWGc9IgogICAgfQogIH0KfQo=
